config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', unlocks: 'unlocks'}
  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

   root 'pages#home'
   resources :posts do
     collection do
       post '/autocomplete', to: 'posts#autocomplete'
       get '/search' => 'posts#search'
       get '/unpublished' => 'posts#unpublished'
       get '/flaged' => 'posts#flaged'
     end
     member do
       post 'send_message', to: 'posts#send_message'
       patch 'publish', to: 'posts#publish'
       get 'flag', to: 'posts#flag'
       post 'unflag', to: 'posts#unflag'
       post 'post_flag', to: 'posts#post_flag'
       get 'reporting', to: 'posts#reporting'
     end
     
   end
   
   resources :users do
     member do
       get 'myposts', to: 'users#myposts'
       delete 'avatar', to: 'users#avatar'
       delete 'image', to: 'users#image'
       get 'report', to: 'users#report'
       post 'unreport', to: 'users#unreport'
       post 'post_report', to: 'users#post_report'
       post 'block', to: 'users#block'
       post 'unblock', to: 'users#unblock'
       get 'reporting', to: 'users#reporting'
     end
     collection do
       get 'settings', to: 'users#settings'
       patch 'update_password', to: 'users#update_password'
       get 'blocked', to: 'users#blocked'
       get 'reported', to: 'users#reported'
       get 'searching_form', to: 'users#searching_form'
       get 'search', to: 'users#search'
     end
   end
  require 'sidekiq/web' 
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
   
   

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :sent_messages, class_name: "Message",
                          foreign_key: "sender_id",
                          dependent: :destroy
  has_many :reply_posts, through: :sent_messages
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  
  has_many :reports, foreign_key: "reported_id",
                     dependent: :destroy
  has_many :reporters, through: :reports, source: :reporter
  scope :desc_order, -> { order(created_at: :desc) }
  scope :desc_report_order, -> { order(report_number: :desc) }
  #has_many :posts, through: :messages
  # validate :albums_count_within_bounds, on: :update
  accepts_nested_attributes_for :albums
  # validates :uid, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :uid, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :async
         
         
    def owner_of?(post)
      if (self.id == post.user_id)
        return true
      else
        return false
      end
    end
    
    def to_param
      self.uid
    end
    
    def follow(other_user)
      active_relationships.create(followed_id: other_user.id)
    end
    
    def following?(other_user)
      following.include?(other_user)
    end
    
    def self.logins_before_captcha
    3
    end
    
    def active_for_authentication?
      super && !self.blocked?
    end
    
    
    private
    

    def find_by_uid(param)
      self.find_by(uid: param)
    end
    # def albums_count_within_bounds
    #   return if self.albums.blank?
    #   errors.add(:base, "Too many photos") if self.albums.size > 1
    # end
    #   def self.logins_before_captcha
    #     3
    #   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_s3_direct_post, only: [:edit]
  invisible_captcha only: [:post_report], honeypot: :verification
  #before_action :admin_user, only: [:index]
  #before_action :correct_user, only: [:show, :edit, :update]

def show
  if @user = User.find_by_uid(params[:id])
    authorize @user
    @album = Album.find_by(user_id: @user.id)
  else
    redirect_to root_url
  end
end

def edit
  if @user = User.find_by_uid(params[:id])
    authorize @user
    @album = @user.albums.build
    @photo = @user.photos.build
    if @user.albums.count > 0 
      @album_existant = @user.albums.first
      # @avatar = Album.find_by(user_id: @user.id).avatar
    else
      @album_existant = nil
    end
    if @user.photos.count > 0 
      @photo_existant = @user.photos.first
      # @avatar = Album.find_by(user_id: @user.id).avatar
    else
      @photo_existant = nil
    end
  else
   redirect_to root_url    
  end
end

def update
  @user = User.find_by_uid(params[:id])
  authorize @user

  if !params.has_key?(:albums) && !params.has_key?(:photos)
    if @user.update_attributes(edit_user_params)
      flash[:success] = 'Your profile was updated'
      redirect_to user_path(@user)
    else
      flash[:danger] = 'An error has occured, Please try again!'
      redirect_to edit_user_path(@user)
    end
  else
    if !params.has_key?(:photos)
      if (@user.update_attributes(edit_user_params) && @user.albums.create(:original_avatar_url => params[:albums]['original_avatar_url'], :user_id => @user.id))
          flash[:success] = 'Your profile and photo was updated'
          redirect_to user_path(@user)
      else
        flash[:danger] = 'An error has occured, Please try again!'
        redirect_to edit_user_path(@user)
      end
    else
      if !params.has_key?(:albums)
        if (@user.update_attributes(edit_user_params) && @user.photos.create(:original_image_url => params[:photos]['original_image_url'], :user_id => @user.id))
            flash[:success] = 'Your profile and photo was updated'
            redirect_to user_path(@user)
        else
          flash[:danger] = 'An error has occured, Please try again!'
          redirect_to edit_user_path(@user)
        end
      else
        if (@user.update_attributes(edit_user_params) && @user.photos.create(:original_image_url => params[:photos]['original_image_url'], :user_id => @user.id) && @user.albums.create(:original_avatar_url => params[:albums]['original_avatar_url'], :user_id => @user.id))
            flash[:success] = 'Your profile and photo was updated'
            redirect_to user_path(@user)
        else
          flash[:danger] = 'An error has occured, Please try again!'
          redirect_to edit_user_path(@user)
        end
      end
    end
  end
end

def avatar
  @user = User.find_by_uid(params[:id])
  authorize @user
  Album.find_by(user_id: @user.id).destroy
  # key = album.original_avatar_url.split('amazonaws.com/')[1]
  # S3_BUCKET.object(key).delete
  # album.destroy
  respond_to do |format|
    format.js
  end
end

def image
  @user = User.find_by_uid(params[:id])
  authorize @user
  Photo.find_by(user_id: @user.id).destroy
  # key = album.original_avatar_url.split('amazonaws.com/')[1]
  # S3_BUCKET.object(key).delete
  # album.destroy
  respond_to do |format|
    format.js
  end
end

def myposts
  if @user = User.find_by_uid(params[:id])
    authorize @user
    @posts = @user.posts.desc_order.paginate(page: params[:page])
  else
    redirect_to root_path
  end
end

def index
  @users = User.desc_order.paginate(page: params[:page])
  authorize User
  get_unpublished_count
  get_flaged_posts_count
  get_reported_users_count
end

def settings
 @user = current_user
end

def update_password
  @user = User.find_by_uid(current_user.id)
  if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case their password changed
    sign_in @user, :bypass => true
    flash[:success] = "Password updated successfully!"
    redirect_to root_path
  else
    flash.now[:danger] = "An error has occured!"
    render "settings"
  end
end

def destroy
  @user = User.find_by_uid(params[:id])
  authorize @user
  if current_user.admin?
    if @user.destroy
      flash[:success] = "User deleted"
      redirect_to root_path
    else
      flash[:danger] = "An error has occured"
      redirect_to root_path
    end
  else
    current_password = ActionController::Base.helpers.sanitize(params[:user][:current_password])
    if @user.valid_password?(current_password) && @user.destroy
    flash[:success] = "User deleted"
    redirect_to root_path
    else
    flash[:danger] = "An error has occured"
    redirect_to root_path
    end
  end
end

def report
  @user = User.find_by_uid(params[:id])
  authorize @user
  if @user.reports(:reporter_id => current_user.id).size == 0
    @report = @user.reports.build(reporter_id: current_user.id)
  else
    flash[:danger] = "User already reported"
    redirect_to user_path(@user)
  end
end

def unreport
  @user = User.find_by_uid(params[:id])
  authorize @user
  @user.update_column(:reported, false) if @user.reported?
  flash[:success] = "User unreported"
  redirect_to reporting_user_path(@user)
end

def post_report
  @user = User.find_by_uid(params[:id])
  authorize @user
  if @user.reports(:reporter_id => current_user.id).size == 0
    @report = @user.reports.build(report_params)
    @report.reporter_id = current_user.id
    if @report.save
      @user.update_column(:reported, true) unless @user.reported?
      @user.update_column(:report_number, (@user.report_number + 1))
      flash[:success] = "Report Sent"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "An error has occured. Please try again"
      render "report"
    end
  end
end

def blocked
  @users = User.where(blocked: true).desc_order.paginate(page: params[:page])
  authorize User
  get_unpublished_count
  get_flaged_posts_count
  get_reported_users_count
  get_blocked_users_count
end


def block
  @user = User.find_by_uid(params[:id])
  authorize @user
  @user.update_column(:blocked, true) unless @user.blocked?
  @user.update_column(:reported, false) if @user.reported?
  flash[:success] = "User Blocked"
  redirect_to reporting_user_path(@user)
end

def unblock
  @user = User.find_by_uid(params[:id])
  authorize @user
  @user.update_column(:blocked, false) if @user.blocked?
  flash[:success] = "User unblocked"
  redirect_to reporting_user_path(@user)
end

def reported
  @users = User.where(reported: true).desc_report_order.paginate(page: params[:page])
  authorize User
  get_unpublished_count
  get_flaged_posts_count
  get_reported_users_count
end

def reporting
  @user = User.find_by_uid(params[:id])
  authorize @user
  @reported_messages = @user.reports
  @sent_messages = @user.sent_messages
  @album = Album.find_by(user_id: @user.id)
end

def searching_form
  authorize User
end

def search
  authorize User
  if !params[:q].blank?
    @user = User.find_by_email(ActionController::Base.helpers.sanitize(params[:q]))
  else
    redirect_to searching_form_users_path
  end
end

    private
      def edit_user_params
        params.require(:user).permit(:username, :date_of_birth, :description, albums_attributes: [:id, :user_id, :original_avatar_url], photos_attributes: [:id, :user_id, :original_image_url])
      end
      
      def user_params
        params.require(:user).permit(:current_password, :password, :password_confirmation)
      end
      
      def set_s3_direct_post
        @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/original/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read', content_length_range: 0..5242880 )
        @s3_direct_post.content_type('image/*')
      end
      
    def report_params
      params.require(:report).permit(:report_message, :verification)
    end
      

      # def deleted_params
      #   params.require(:user).permit(:current_password)
      # end

      # def create_album_params
      #   params.require(:user).permit(albums_attributes: [:id, :user_id, :avatar])
      # end
      
      # def correct_user
      #   @user = User.find(params[:id])
      #   redirect_to (root_url) unless (current_user == @user)
      # end

end

app/views/users/blocked.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Users</h1>
		    <div class="btn-group" role="group" aria-label="Default Button Groups">
  	    <%= link_to "All posts", posts_path, class: "btn btn-default" %>
  	    <%= link_to "Waiting (#{@unpublished_posts})", unpublished_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Posts(#{@flaged_posts})", flaged_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Users(#{@reported_users})", reported_users_path, class: "btn btn-default" %>
  	    <%= link_to "Blocked Users(#{@blocked_users})", blocked_users_path, class: "btn btn-default-active" %>
  	    <%= link_to "Search for a user", searching_form_users_path, class: "btn btn-default" %>
  	    <%= link_to "Users", users_path, class: "btn btn-default" %>
        </div>
      <% if !@users.blank? %>
      <%= will_paginate %>
      <div class="list-group">
        <%= render @users %>
      </div>
      <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Our eyes met</h3>
  </div>
  <div class="panel-body">
    <%= form_for(@user, :html => { :html => { :multipart => true }, class: 'directUpload form-group', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }}) do |f| %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control', autofocus: true, placeholder: "Precise your username" %>
      
      <%= f.label :date_of_birth %>
      <%= f.date_field :date_of_birth, class: 'form-control', id: "date-of-birth" %>
      </br>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      
      
  
  <%= f.fields_for(@album) do |p| %>
     <div class="field">
       <%= p.label :avatar %><br>
       <% if @album_existant.blank? %>
         <%= p.file_field :original_avatar_url, name: "albums[original_avatar_url]", id: "file-field", accept: 'image/png,image/gif,image/jpeg', disabled: false %>
       <% else %>
          <%= p.file_field :original_avatar_url, name: "albums[original_avatar_url]", id: "file-field", accept: 'image/png,image/gif,image/jpeg', disabled: true %>
       <% end %>
     </div>
  <% end %>
 
   <div class="row">
     
      <% if !@album_existant.blank? %>
        <% if @album_existant.image_processing == true %>
        <div class="col-xs-6 col-md-3 imgLiquidFill imgLiquid" style="width:250px; height:250px;">
          <%= image_tag("http://placehold.it/770x400&text=processing", class: "image-preview") %>
        </div>  
        <% else %>

        <div class="col-xs-6 col-md-3 imgLiquidFill imgLiquid" style="width:250px; height:250px;">
          <%= image_tag(@album_existant.avatar.thumb.url, class: "image-preview") %>
        </div>

        <% end %>
      <% else %>
      <div class="col-xs-6 col-md-3 imgLiquidFill imgLiquid" style="width:250px; height:250px;">
       <%= image_tag("default-profile.png", class: "image-preview") %>
      </div>
      <% end %>
     
     <div class="col-xs-6 col-md-9">
       <% if !@album_existant.blank? && @album_existant.image_processing == nil %>
       <%= link_to "Delete avatar", avatar_user_path(@user), class: "delete-button", remote: true, method: :delete %>
       <% end %>
     </div>
   </div>
   
     <%= f.fields_for(@photo) do |p| %>
     <div class="field">
       <%= p.label :image %><br>
       <% if @photo_existant.blank? %>
         <%= p.file_field :original_image_url, name: "photos[original_image_url]", id: "photo-file-field", accept: 'image/png,image/gif,image/jpeg', disabled: false %>
       <% else %>
          <%= p.file_field :original_image_url, name: "photos[original_image_url]", id: "photo-file-field", accept: 'image/png,image/gif,image/jpeg', disabled: true %>
       <% end %>
     </div>
  <% end %>
   
   <div class="row">
     
      <% if !@photo_existant.blank? %>
        <% if @photo_existant.image_processing == true %>
        <div class="col-xs-6 col-md-3 imgLiquidFill imgLiquid photo" style="width:250px; height:250px;">
          <%= image_tag("http://placehold.it/770x400&text=processing", class: "photo-preview") %>
        </div>  
        <% else %>

        <div class="col-xs-6 col-md-3 imgLiquidFill imgLiquid photo" style="width:250px; height:250px;">
          <%= image_tag(@photo_existant.image.thumb.url, class: "photo-preview") %>
        </div>

        <% end %>
      <% else %>
      <div class="col-xs-6 col-md-3 imgLiquidFill imgLiquid photo" style="width:250px; height:250px;">
       <%= image_tag("default-profile.png", class: "photo-preview") %>
      </div>
      <% end %>
     
     <div class="col-xs-6 col-md-9">
       <% if !@photo_existant.blank? && @photo_existant.image_processing == nil %>
       <%= link_to "Delete Photo", image_user_path(@user), class: "photo-delete-button", remote: true, method: :delete %>
       <% end %>
     </div>
 
   </div>
   
   
      
      <%= f.submit "Save your profile", class: "btn btn-primary" %>
    <% end %>
    

        

  </div>
</div>



<script>

$(document).ready(function() {
    $(".imgLiquidFill").imgLiquid({
        fill: false,
        horizontalAlign: "center",
        verticalAlign: "50%"
    });
});

$(function() {
  "use strict";
  $('.directUpload').find("input:file").each(function(i, elem) {
    var fileInput    = $(elem);
    var form         = $(fileInput.parents('form:first'));
    var submitButton = form.find('input[type="submit"]');
    var progressBar  = $("<div class='bar'></div>");
    var barContainer = $("<div class='progress'></div>").append(progressBar);
    fileInput.after(barContainer);
    fileInput.fileupload({
      add: function (e, data) {
        var uploadErrors = [];

        var acceptFileTypes = /(\.|\/)(gif|jpe?g|png)$/i;
        if(data.originalFiles[0]['type'].length && !acceptFileTypes.test(data.originalFiles[0]['type'])) {
            uploadErrors.push('File Type not accepted');
        }

        console.log(data.originalFiles[0]['size']) ;
        if (data.originalFiles[0]['size'] > 5 * 1024 * 1024) {
            uploadErrors.push('File is too large');
        }
        if(uploadErrors.length > 0) {
            alert(uploadErrors.join("\n"));
        } else {
            data.submit();
        }
        
        
    },
      fileInput:       fileInput,
      url:             form.data('url'),
      type:            'POST',
      autoUpload:       true,
      // acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
      // maxFileSize: 1000,
      formData:         form.data('form-data'),
      paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
      dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
      replaceFileInput: false,
      progressall: function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        progressBar.css('width', progress + '%')
      },
      start: function (e) {
        submitButton.prop('disabled', true);

        progressBar.
          css('background', 'green').
          css('display', 'block').
          css('width', '0%').
          text("Loading...");
      },
      done: function(e, data) {
        submitButton.prop('disabled', false);
        fileInput.prop('disabled', true);
        // $('#file-field').prop('disabled', true);
        progressBar.text("Uploading done");
        // extract key and generate URL from response
        var key   = $(data.jqXHR.responseXML).find("Key").text();
        var url   = '//' + form.data('host') + '/' + key;
        
        // create hidden field
        var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url });
        // form.append(input);
        input.insertBefore(".btn");
      },
      fail: function(e, data) {
        submitButton.prop('disabled', false);

        progressBar.
          css("background", "red").
          text("Failed");
      }
    });
  });
});

// $("#file-field").bind("change", function(){
//   if (this.files && this.files[0]){
//   var size_in_megabytes = this.files[0].size/1024/1024;
//   if (size_in_megabytes > 1) {
//     alert('Maximum file size is 5MB. Please choose a smaller file.');
//   }
//   }
  
// });


$("#file-field").change(function(){
    var acceptedFileTypes = /(\.|\/)(gif|jpe?g|png)$/i;
    if (this.files && this.files[0] && this.files[0].size/1024/1024 < 5 && acceptedFileTypes.exec(this.files[0]['type'])) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.image-preview').attr('src', e.target.result);
        $('.imgLiquidFill').imgLiquid({
        fill: false,
        horizontalAlign: "center",
        verticalAlign: "50%"
        });
      }
      reader.readAsDataURL(this.files[0]);
    }
});



$("#photo-file-field").change(function(){
    var acceptedFileTypes = /(\.|\/)(gif|jpe?g|png)$/i;
    if (this.files && this.files[0] && this.files[0].size/1024/1024 < 5 && acceptedFileTypes.exec(this.files[0]['type'])) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('.photo-preview').attr('src', e.target.result);
        $('.photo').imgLiquid({
        fill: false,
        horizontalAlign: "center",
        verticalAlign: "50%"
        });
      }
      reader.readAsDataURL(this.files[0]);
    }
});
</script>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Users</h1>
		    <div class="btn-group" role="group" aria-label="Default Button Groups">
  	    <%= link_to "All posts", posts_path, class: "btn btn-default" %>
  	    <%= link_to "Waiting (#{@unpublished_posts})", unpublished_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Posts(#{@flaged_posts})", flaged_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Users(#{@reported_users})", reported_users_path, class: "btn btn-default" %>
  	    <%= link_to "Blocked Users", blocked_users_path, class: "btn btn-default" %>
  	    <%= link_to "Search for a user", searching_form_users_path, class: "btn btn-default" %>
  	    <%= link_to "Users", users_path, class: "btn btn-default-active" %>
        </div>
      <% if !@users.blank? %>
      <%= will_paginate %>
      <div class="list-group">
        <%= render @users %>
      </div>
      <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/report.html.erb
  <%= form_for(@report, url: post_report_user_path(@user)) do |f| %>
  <div class="form-group">
  <%= f.text_area :report_message, class: "form-control", placeholder: "write a message" %>
  <%= f.invisible_captcha :verification %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  </div>

app/views/users/reported.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Users</h1>
		    <div class="btn-group" role="group" aria-label="Default Button Groups">
  	    <%= link_to "All posts", posts_path, class: "btn btn-default" %>
  	    <%= link_to "Waiting (#{@unpublished_posts})", unpublished_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Posts(#{@flaged_posts})", flaged_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Users(#{@reported_users})", reported_users_path, class: "btn btn-default-active" %>
  	    <%= link_to "Blocked Users", blocked_users_path, class: "btn btn-default" %>
  	    <%= link_to "Search for a user", searching_form_users_path, class: "btn btn-default" %>
  	    <%= link_to "Users", users_path, class: "btn btn-default" %>
        </div>
      <% if !@users.blank? %>
      <%= will_paginate %>
      <div class="list-group">
        <%= render @users %>
      </div>
      <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/reporting.html.erb
<% if @album.blank? %>
  <%= render 'user_partial/show_0' %>
<% else %>
  <%= render 'user_partial/show_1' %>
<% end %>

<div>
<% if current_user.admin? %>
  <% if !@user.blocked? %>
    <%= button_to("Block This User", block_user_path(@user), method: :post, data: { confirm: 'Are you certain you want to block this?' }) %>
  <% else %>
    <%= button_to("Unlock This User", unblock_user_path(@user), method: :post, data: { confirm: 'Are you certain you want to unblock this?' }) %>  
  <% end %>
  <% if @user.reported? %>
    <%= button_to("Unreport This User", unreport_user_path(@user), method: :post, data: { confirm: 'Are you certain you want to unreport this?' }) %>
  <% end %>
    <%= button_to("Delete This User", user_path(@user), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }) %>
    <%= link_to("All the posts of the user: (#{@user.posts.size})", myposts_user_path(@user), :method => :get) %>
<% end %>
</div>

<% if !@reported_messages.blank? %>
<div> Reported messages: <%= @reported_messages.size %></div>
<div>
  <% @reported_messages.each do |report| %>
    <%= report.report_message %>
    <%= report.created_at %>
  <% end %>
</div>
<% end %>

<% if !@sent_messages.blank? %>
<div> Sent Messsages</div>
<div>
  <% @sent_messages.each do |msg| %>
    <%= msg.content %>
    <%= msg.created_at %>
  <% end %>
</div>
<% end %>

app/views/users/search.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Users</h1>
		    <div class="row">
          <div class="col-md-6">
            <%= form_tag(search_users_path, method: :get) do %>
            <div class="input-group">
              <%= text_field_tag(:q, params[:q], placeholder: 'Search for', class: 'form-control') %>
              <span class="input-group-btn">
                <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
              </span>
            </div><!-- /input-group -->
            <% end %>
          </div>
          <div class="col-md-6">
          </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
      <% if !@user.blank? %>
        <%= link_to reporting_user_path(@user), class: "list-group-item" do %>
          <div class="media col-md-3">
            <figure>
              <% if !@user.albums.blank? %>
              <%= image_tag(@user.albums.first.avatar.thumb.url, class: "media-object img-rounded img-responsive", id: "avatar-post") %>
              <% else %>
              <img class="media-object img-rounded img-responsive"  id="avatar-post" src="http://placehold.it/350x250" alt="placehold.it/350x250">
              <% end %>
            </figure>
          </div>
          <div class="col-md-7">
            <h4 class="list-group-item-heading"><%= @user.email %></h4>
            <p class="list-group-item-text">
              <small id="city-user-profile">
                <cite><%= @user.gender %> - <%= @user.date_of_birth %>
                <i class="glyphicon glyphicon-map-marker show-user-glyphicon"></i>
                </cite>
              </small>
              <%=h truncate(@user.description, length: 40) %>
            </p>
          </div>
          <div class="col-md-2">
            
            <p><%= @user.created_at %></p>
        
          </div>
          <div class="clearfix"></div>
        <% end %>
      <% else %>
        <p>No user found</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/searching_form.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Users</h1>
		    <div class="row">
          <div class="col-md-6">
            <%= form_tag(search_users_path, method: :get) do %>
            <div class="input-group">
              <%= text_field_tag(:q, params[:q], placeholder: 'Search for', class: 'form-control') %>
              <span class="input-group-btn">
                <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
              </span>
            </div><!-- /input-group -->
            <% end %>
          </div>
          <div class="col-md-6">
          </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
    </div>
  </div>
</div>