config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', unlocks: 'unlocks'}
  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

   root 'pages#home'
   resources :posts do
     collection do
       post '/autocomplete', to: 'posts#autocomplete'
       get '/search' => 'posts#search'
       get '/unpublished' => 'posts#unpublished'
       get '/flaged' => 'posts#flaged'
     end
     member do
       post 'send_message', to: 'posts#send_message'
       patch 'publish', to: 'posts#publish'
       get 'flag', to: 'posts#flag'
       post 'unflag', to: 'posts#unflag'
       post 'post_flag', to: 'posts#post_flag'
       get 'reporting', to: 'posts#reporting'
     end
     
   end
   
   resources :users do
     member do
       get 'myposts', to: 'users#myposts'
       delete 'avatar', to: 'users#avatar'
       delete 'image', to: 'users#image'
       get 'report', to: 'users#report'
       post 'unreport', to: 'users#unreport'
       post 'post_report', to: 'users#post_report'
       post 'block', to: 'users#block'
       post 'unblock', to: 'users#unblock'
       get 'reporting', to: 'users#reporting'
     end
     collection do
       get 'settings', to: 'users#settings'
       patch 'update_password', to: 'users#update_password'
       get 'blocked', to: 'users#blocked'
       get 'reported', to: 'users#reported'
       get 'searching_form', to: 'users#searching_form'
       get 'search', to: 'users#search'
     end
   end
  require 'sidekiq/web' 
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
   
   

end

app/views/pages/_header.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">

<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "I met You", root_path, class: "navbar-brand" %>
</div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"></ul>
      <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "New Post", new_post_path %></li>
              <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Your Menu" %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", user_path(current_user) %></li>
                  <li><%= link_to "My Posts", myposts_user_path(current_user) %></li>
                  <li><%= link_to "Settings", settings_users_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
                </ul>
              </li>
              <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            </ul>
      <% else %>
            <%= render 'devise/sessions/signin' %>
      <% end %>
            
      
</div>

</div>
</nav>

app/views/pages/home.html.erb
<div class="container">
<div class="row">
    <div class="col-md-7">
        
    </div>
    

    
    <div class="col-md-5">
    <%= render 'devise/registrations/signup' %>
    </div>
    

</div>  
</div>