config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', unlocks: 'unlocks'}
  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

   root 'pages#home'
   resources :posts do
     collection do
       post '/autocomplete', to: 'posts#autocomplete'
       get '/search' => 'posts#search'
       get '/unpublished' => 'posts#unpublished'
       get '/flaged' => 'posts#flaged'
     end
     member do
       post 'send_message', to: 'posts#send_message'
       patch 'publish', to: 'posts#publish'
       get 'flag', to: 'posts#flag'
       post 'unflag', to: 'posts#unflag'
       post 'post_flag', to: 'posts#post_flag'
       get 'reporting', to: 'posts#reporting'
     end
     
   end
   
   resources :users do
     member do
       get 'myposts', to: 'users#myposts'
       delete 'avatar', to: 'users#avatar'
       delete 'image', to: 'users#image'
       get 'report', to: 'users#report'
       post 'unreport', to: 'users#unreport'
       post 'post_report', to: 'users#post_report'
       post 'block', to: 'users#block'
       post 'unblock', to: 'users#unblock'
       get 'reporting', to: 'users#reporting'
     end
     collection do
       get 'settings', to: 'users#settings'
       patch 'update_password', to: 'users#update_password'
       get 'blocked', to: 'users#blocked'
       get 'reported', to: 'users#reported'
       get 'searching_form', to: 'users#searching_form'
       get 'search', to: 'users#search'
     end
   end
  require 'sidekiq/web' 
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
   
   

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!
before_action :confirmed_user, only: [:new, :create, :send_message, :edit, :update, :flag, :post_flag]
# before_action :get_unpublished_count, only: [:unpublished]
# before_action :get_flaged_posts_count, only: [:unpublished]
# before_action :get_reported_users_count, only: [:unpublished]
#before_action :admin_user, only: [:unpublished, :publish, :flaged]
invisible_captcha only: [:send_message, :create, :post_flag], honeypot: :verification

  def new
    @post = current_user.posts.build
    authorize @post
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @post = current_user.posts.build(post_params)
    authorize @post
    @post.gender = current_user.gender
    if @post.save
      flash[:success] = "Post created"
      redirect_to @post
    else
      flash.now[:danger] = "An error has occured. Please try again"
      render "new"
    end
  end
  
  def show
    @post = Post.friendly.find(params[:id])
    authorize @post
    if current_user.reply_posts.include?(@post) || current_user.owner_of?(@post)
      @message = nil
    else
      @message = current_user.sent_messages.build(reply_post_id: @post.id)
    end
  end
  

  def index
    if current_user.admin?
      @posts = policy_scope(Post.desc_order.paginate(page: params[:page]))
      get_unpublished_count
      get_flaged_posts_count
      get_reported_users_count
    else
      case current_user.gender when "M"
        @posts = policy_scope(Post.where(:gender => "F").desc_order.paginate(page: params[:page]))
      else
        @posts = policy_scope(Post.where(:gender => "M").desc_order.paginate(page: params[:page]))
      end
    end
  end
  
  def autocomplete
    # if !($redis.try(:any?))
    # (JSON.parse(File.read("#{Rails.root}/public/03V16_third.json")))["cp_autocomplete"].each.with_index(1) do |f, index|
    #   $redis.hset 'postal-data', index.to_s, f.to_json
    # end

    # (JSON.parse(File.read("#{Rails.root}/public/03V16_third.json")))["cp_autocomplete"].each.with_index(1) do |f, index|
    #   (2..4).each do |n|
    #     prefix = (f['CP'][0..n]).to_s
    #     $redis.zadd("postal:#{prefix}", [0, index.to_s])
    #   end
    # end

    # # (JSON.parse(File.read("#{Rails.root}/public/03V16_third.json")))["cp_autocomplete"].each do |f|
    # #   f["CITY_PAR"] = f['VILLE'].parameterize
    # # end

    # (JSON.parse(File.read("#{Rails.root}/public/03V16_third.json")))["cp_autocomplete"].each.with_index(1) do |f, index|
    #   (2..(((f['VILLE'].parameterize).length)-1)).each do |n|
    #     prefix = ((f['VILLE'].parameterize)[0..n]).to_s.downcase
    #     $redis.zadd("city:#{prefix}", [0, index.to_s])
    #   end
    # end
    
    # end
    require 'auto_compeletion_cp_city'
    if !ActionController::Base.helpers.sanitize(params[:codePostal]).blank?
      # search_term = ActionController::Base.helpers.sanitize(params[:codePostal])
      range = $redis.zrange "postal:#{ActionController::Base.helpers.sanitize(params[:codePostal])}", 0, 3
      @list = []
        if !range.blank?
          case range.length
          when 1
            t = $redis.hmget 'postal-data', range[0]
          when 2
            t = $redis.hmget 'postal-data', range[0], range[1]
          when 3
            t = $redis.hmget 'postal-data', range[0], range[1], range[2]
          else
            t = $redis.hmget 'postal-data', range[0], range[1], range[2], range[3]
          end
          t.map! do |n|
            JSON.parse(n)
          end
          t.each do |m|
            break if m.blank?
            selected = AutoCompletionCpCity.new
            selected.CodePostal = m['CP']
            selected.Ville = m['VILLE']
            selected.Lat = m['LATITUDE']
            selected.Lon = m['LONGITUDE']
            @list << selected
          end
        end
    else
        if !(ActionController::Base.helpers.sanitize(params[:ville]).blank?)
          # search_term = ActionController::Base.helpers.sanitize(params[:ville]).parameterize.downcase
          range = $redis.zrange "city:#{ActionController::Base.helpers.sanitize(params[:ville]).parameterize.downcase}", 0, 3
          @list = []
          if !range.blank?
            case range.length
            when 1
              t = $redis.hmget 'postal-data', range[0]
            when 2
              t = $redis.hmget 'postal-data', range[0], range[1]
            when 3
              t = $redis.hmget 'postal-data', range[0], range[1], range[2]
            else
              t = $redis.hmget 'postal-data', range[0], range[1], range[2], range[3]
            end
            t.map! do |n|
              JSON.parse(n)
            end
            t.each do |m|
              break if m.blank?
              selected = AutoCompletionCpCity.new
              selected.CodePostal = m['CP']
              selected.Ville = m['VILLE']
              selected.Lat = m['LATITUDE']
              selected.Lon = m['LONGITUDE']
              @list << selected
            end
          end
        end
    end

    # ActiveSupport::Dependencies.remove_const(DATA)
    # $redis.get('postal')
    # require 'auto_compeletion_cp_city'
    # @list = []
    # if !(ActionController::Base.helpers.sanitize(params[:codePostal]).blank?)
    #   search_term = ActionController::Base.helpers.sanitize(params[:codePostal])
    #   search = /\A#{search_term}/
    #       DATA["cp_autocomplete"].each do |f|
    #         if search.match("#{f['CP']}",0) && (@list.length < 4)
    #           selected = AutoCompletionCpCity.new
    #           selected.CodePostal = f['CP']
    #           selected.Ville = f['VILLE']
    #           @list << selected
    #         end
    #       end
    # else
    #   if !(ActionController::Base.helpers.sanitize(params[:ville]).blank?)
    #   search_term = ActionController::Base.helpers.sanitize(params[:ville]).parameterize
    #   search = /\A#{Regexp.escape(search_term)}/i
    #   DATA["cp_autocomplete"].each do |f|
    #         if search.match("#{f['CITY_PAR']}",0) && (@list.length < 4) 
    #           selected = AutoCompletionCpCity.new
    #           selected.CodePostal = f['CP']
    #           selected.Ville = f['VILLE']
    #           @list << selected
    #         end
    #   end
    #   end
    # end
    
    respond_to do |format|
      format.json { 
        render json: @list
      }
    end
  end
  
  def search
    if params[:q].blank? && params[:postal].blank?
      redirect_to root_path
    else
      if params[:postal].blank?
        # query = ActionController::Base.helpers.sanitize(params[:q])
        if current_user.admin?
          @posts = Post.admin_search(ActionController::Base.helpers.sanitize(params[:q])).records.paginate(page: params[:page])
        else
          case current_user.gender when "M"
            @posts = Post.male_search(ActionController::Base.helpers.sanitize(params[:q])).records.paginate(page: params[:page])
          else
            @posts = Post.female_search(ActionController::Base.helpers.sanitize(params[:q])).records.paginate(page: params[:page])
          end
        end
      else
        if params[:q].blank?
          if (params[:postal].length == 5) && (!params[:maxlat].blank?) && (!params[:minlon].blank?) && (!params[:minlat].blank?) && (!params[:maxlon].blank?)
            # maxlat = ActionController::Base.helpers.sanitize(params[:maxlat])
            # minlon = ActionController::Base.helpers.sanitize(params[:minlon])
            # minlat = ActionController::Base.helpers.sanitize(params[:minlat])
            # maxlon = ActionController::Base.helpers.sanitize(params[:maxlon])
            if current_user.admin?
              @posts = Post.geo_only_admin_search(ActionController::Base.helpers.sanitize(params[:maxlat]), ActionController::Base.helpers.sanitize(params[:minlon]), ActionController::Base.helpers.sanitize(params[:minlat]), ActionController::Base.helpers.sanitize(params[:maxlon])).records.paginate(page: params[:page])
            else
              case current_user.gender when "M"
                @posts = Post.geo_only_male_search(ActionController::Base.helpers.sanitize(params[:maxlat]), ActionController::Base.helpers.sanitize(params[:minlon]), ActionController::Base.helpers.sanitize(params[:minlat]), ActionController::Base.helpers.sanitize(params[:maxlon])).records.paginate(page: params[:page])
              else
                @posts = Post.geo_only_female_search(ActionController::Base.helpers.sanitize(params[:maxlat]), ActionController::Base.helpers.sanitize(params[:minlon]), ActionController::Base.helpers.sanitize(params[:minlat]), ActionController::Base.helpers.sanitize(params[:maxlon])).records.paginate(page: params[:page])
              end
            end
          end
        else
          if (params[:postal].length == 5) && (!params[:maxlat].blank?) && (!params[:minlon].blank?) && (!params[:minlat].blank?) && (!params[:maxlon].blank?)
            # query = ActionController::Base.helpers.sanitize(params[:q])
            # maxlat = ActionController::Base.helpers.sanitize(params[:maxlat])
            # minlon = ActionController::Base.helpers.sanitize(params[:minlon])
            # minlat = ActionController::Base.helpers.sanitize(params[:minlat])
            # maxlon = ActionController::Base.helpers.sanitize(params[:maxlon])
            if current_user.admin?
              @posts = Post.geo_admin_search(ActionController::Base.helpers.sanitize(params[:q]), ActionController::Base.helpers.sanitize(params[:maxlat]), ActionController::Base.helpers.sanitize(params[:minlon]), ActionController::Base.helpers.sanitize(params[:minlat]), ActionController::Base.helpers.sanitize(params[:maxlon])).records.paginate(page: params[:page])
            else
              case current_user.gender when "M"

app/helpers/posts_helper.rb
module PostsHelper
  
  def owner(post)
      if (current_user.id == post.user_id)
        return true
      else
        return false
      end
  end
end

app/views/posts/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/posts/_post_unpublished.html.erb
<div class="list-group-item">
  <div class="media col-md-3">
    <figure>
      <% if !post.user.albums.blank? %>
      <%= image_tag(post.user.albums.first.avatar.thumb.url, class: "media-object img-rounded img-responsive", id: "avatar-post") %>
      <% else %>
      <%= image_tag('thumb.png', class: "media-object img-rounded img-responsive",  id: "avatar-post") %>
      <% end %>
    </figure>
  </div>
  <div class="col-md-7">
    <h4 class="list-group-item-heading"><%= link_to post.title, reporting_post_path(post) %></h4>
    <p class="list-group-item-text">
      <small id="city-user-profile">
        <cite><%= post.city %> - <%= post.postal_code %>
        <i class="glyphicon glyphicon-map-marker show-user-glyphicon"></i>
        </cite>
      </small>
      <%=h truncate(post.description, length: 40) %>
    </p>
  </div>
  <div class="col-md-2">
    <i class="glyphicon glyphicon-heart-empty"></i>
    <p><%=l post.meeting_date %></p>
    <% if current_user.admin? && !post.published? %>
    <%= button_to("Publish", publish_post_path(post), :params => {:published => "protect"}, :method => :patch) %>
    <% end %>
  </div>

  <div class="clearfix"></div>
</div>

app/views/posts/flag.html.erb
  <%= form_for(@flag, url: post_flag_post_path(@post)) do |f| %>
  <div class="form-group">
  <%= f.text_area :flag_message, class: "form-control", placeholder: "write a message" %>
  <%= f.invisible_captcha :verification %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  </div>

app/views/posts/flaged.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Posts</h1>
        <div class="btn-group" role="group" aria-label="Default Button Groups">
        <% if current_user.admin? %>
  	    <%= link_to "All posts", posts_path, class: "btn btn-default" %>
  	    <%= link_to "Waiting (#{@unpublished_posts})", unpublished_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Posts(#{@flaged_posts})", flaged_posts_path, class: "btn btn-default-active" %>
  	    <%= link_to "Signaled Users(#{@reported_users})", reported_users_path, class: "btn btn-default" %>
  	    <%= link_to "Blocked Users", blocked_users_path, class: "btn btn-default" %>
  	    <%= link_to "Search for a user", searching_form_users_path, class: "btn btn-default" %>
  	    <%= link_to "Users", users_path, class: "btn btn-default" %>
        <% end %>
        </div>
      <% if !@posts.blank? %>
      <%= will_paginate %>
      <div class="list-group">
        <%= render partial: 'posts/post_reporting', collection: @posts, as: :post %>
      </div>
      <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Posts</h1>
		    <div class="row">
          <div class="col-md-6">
            <%= form_tag(search_posts_path, method: :get) do %>
            <div class="input-group">
              <%= text_field_tag(:q, params[:q], placeholder: 'Search for', class: 'form-control') %>
              <%= text_field_tag(:postal, params[:postal], placeholder: 'Code Postal ou ville', id: 'search_location', class: 'form-control') %>
              <%= text_field_tag(nil, nil, id: 'search_city', class: 'form-control', readonly: 'readonly') %>
              <div style="margin-bottom: 20px" class="input-group" id="radio-distance">
                <%= label_tag 'distance', "Distance:", class: "radio-inline", style:"font-weight: bold; margin-left: -15px" %>
                <%= label_tag 'distance_10', "10 km", class: "radio-inline" %>
                <%= radio_button_tag 'distance', '10', true, class: "radio-inline", style: "margin-right: 5px" %>
                <%= label_tag 'distance_50', "50 km", class: "radio-inline" %>
                <%= radio_button_tag 'distance', '50', false, class: "radio-inline", style: "margin-right: 5px"  %>
              </div>
              <%= hidden_field_tag(:maxlat, params[:maxlat], id:'max_lat') %>
              <%= hidden_field_tag(:minlon, params[:minlon], id:'min_lon') %>
              <%= hidden_field_tag(:minlat, params[:minlat], id:'min_lat') %>
              <%= hidden_field_tag(:maxlon, params[:maxlon], id:'max_lon') %>
              <span class="input-group-btn">
                <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
              </span>

              <%= hidden_field_tag(nil, nil, id:'search_lat') %>
              <%= hidden_field_tag(nil, nil, id:'search_lon') %>
            </div><!-- /input-group -->
            <% end %>
          </div>
          <div class="col-md-6">
          </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
        
        <div class="btn-group" role="group" aria-label="Default Button Groups">
        <% if current_user.admin? %>
  	    <%= link_to "All posts", posts_path, class: "btn btn-default-active" %>
  	    <%= link_to "Waiting (#{@unpublished_posts})", unpublished_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Posts(#{@flaged_posts})", flaged_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Users(#{@reported_users})", reported_users_path, class: "btn btn-default" %>
  	    <%= link_to "Blocked Users", blocked_users_path, class: "btn btn-default" %>
  	    <%= link_to "Search for a user", searching_form_users_path, class: "btn btn-default" %>
  	    <%= link_to "Users", users_path, class: "btn btn-default" %>
        <% end %>
        </div>
        
      <% if !@posts.blank? %>
      <%= will_paginate %>
      <div class="list-group">
        <%= render policy_scope(@posts) %>
      </div>
      <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_tag do -%>

$(document).ready(function(){
  $('#search_city').hide();
  $('#radio-distance').hide();
});

$(function ()
{
  var cache = {};
	$("#search_location").autocomplete({
		source: function (request, response)
		 {
		   var term = request.term;
  		   if (term in cache)
  			{
  				response($.map(cache[ term ], function (item)
  				{
  
  					return {
  						label: item.CodePostal + ", " + item.Ville,
  						value: function ()
  						{
  								$('#search_lat').val(item.Lat);
  								$('#search_lon').val(item.Lon);
  								$('#search_city').val(item.Ville).trigger('change');
  								return item.CodePostal;
  						}
  					}
  				}));
  			}
  			else
  			{
  			var objData = {};
        if (!isNaN(term))
        {
        	objData = { codePostal: request.term, pays: 'FR', maxRows: 10 };
        }
        else
          {
          	objData = { ville: request.term, pays: 'FR', maxRows: 10 };
          }
          $.ajax({
          url: '/posts/autocomplete.json',
          dataType: "json",
          data: objData,
          type: 'POST',
          success: function (data)
          {
            cache[term] = data ;
          	response($.map(data, function (item)
          	{
          
          		return {
          			label: item.CodePostal + ", " + item.Ville,
          			value: function ()
          			{
          			  $('#search_lat').val(item.Lat);
  								$('#search_lon').val(item.Lon);
  								$('#search_city').val(item.Ville).trigger('change');
  								return item.CodePostal;
          			}
          		}
          	}));
      }
});

}
		},
		minLength: 3,
		delay: 400
	});
});

$('#search_city').on('change',function(){
$('#search_city').show();
$('#radio-distance').show();
$('#distance_10').click();
});

$('#search_location').keyup(function(){
if( $(this).val().length === 0 ) {
  $('#search_city').val('');
  $('#search_city').hide();
  $('#radio-distance').hide();
}
});

getBoundingBox = function (centerPoint, distance) {
  var MIN_LAT, MAX_LAT, MIN_LON, MAX_LON, R, radDist, degLat, degLon, radLat, radLon, minLat, maxLat, minLon, maxLon, deltaLon;
  if (distance < 0) {
    return 'Illegal arguments';
  }
  // helper functions (degrees<–>radians)
  Number.prototype.degToRad = function () {
    return this * (Math.PI / 180);
  };
  Number.prototype.radToDeg = function () {
    return (180 * this) / Math.PI;
  };
  // coordinate limits
  MIN_LAT = (-90).degToRad();
  MAX_LAT = (90).degToRad();
  MIN_LON = (-180).degToRad();
  MAX_LON = (180).degToRad();
  // Earth's radius (km)
  R = 6378.1;
  // angular distance in radians on a great circle
  radDist = distance / R;
  // center point coordinates (deg)
  degLat = centerPoint[0];
  degLon = centerPoint[1];
  // center point coordinates (rad)
  radLat = degLat.degToRad();
  radLon = degLon.degToRad();
  // minimum and maximum latitudes for given distance
  minLat = radLat - radDist;
  maxLat = radLat + radDist;
  // minimum and maximum longitudes for given distance
  minLon = void 0;
  maxLon = void 0;
  // define deltaLon to help determine min and max longitudes
  deltaLon = Math.asin(Math.sin(radDist) / Math.cos(radLat));
  if (minLat > MIN_LAT && maxLat < MAX_LAT) {
    minLon = radLon - deltaLon;
    maxLon = radLon + deltaLon;
    if (minLon < MIN_LON) {
      minLon = minLon + 2 * Math.PI;
    }
    if (maxLon > MAX_LON) {
      maxLon = maxLon - 2 * Math.PI;
    }
  }
  // a pole is within the given distance
  else {
    minLat = Math.max(minLat, MIN_LAT);
    maxLat = Math.min(maxLat, MAX_LAT);
    minLon = MIN_LON;
    maxLon = MAX_LON;
  }
  return [
    minLon.radToDeg(),
    minLat.radToDeg(),
    maxLon.radToDeg(),
    maxLat.radToDeg()
  ];
};

$("#distance_10").on('click', function(){
  var distance = 10;
  var latPoint = parseFloat($("#search_lat").val());
  var lonPoint = parseFloat($("#search_lon").val());
  var PosArray = [latPoint, lonPoint];
  $('#min_lon').val((getBoundingBox(PosArray, distance)[0]).toFixed(4));
  $('#min_lat').val((getBoundingBox(PosArray, distance)[1]).toFixed(4));
  $('#max_lon').val((getBoundingBox(PosArray, distance)[2]).toFixed(4));
  $('#max_lat').val((getBoundingBox(PosArray, distance)[3]).toFixed(4));
});

$("#distance_50").on('click', function(){
  var distance = 50;
  var latPoint = parseFloat($("#search_lat").val());
  var lonPoint = parseFloat($("#search_lon").val());
  var PosArray = [latPoint, lonPoint];
  $('#min_lon').val((getBoundingBox(PosArray, distance)[0]).toFixed(4));
  $('#min_lat').val((getBoundingBox(PosArray, distance)[1]).toFixed(4));
  $('#max_lon').val((getBoundingBox(PosArray, distance)[2]).toFixed(4));
  $('#max_lat').val((getBoundingBox(PosArray, distance)[3]).toFixed(4));
});


<% end -%>

app/views/posts/reporting.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><b><%= @post.title %></b></h3>
  </div>
  <div class="panel-body">
    <p><b>City: </b><%= @post.city %> - <b>Postal code: </b><%= @post.postal_code %></p>
    <p><b>Meeting date: </b><%= l @post.meeting_date %></p>
    <p><b>Description: </b></p>
    <p><%= simple_format(@post.description) %></p>
  </div>
    <div class="panel-footer">
    <small>
    <span class="glyphicon glyphicon-time"></span>
    Posted <%= timeago(@post.created_at) %>
    </small>
    </div>
</div>

<% if current_user.admin? %>
    <%= link_to("Edit The Post", edit_post_path(@post), :method => :get) %>
    <%= button_to("Delete The Post", post_path(@post), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }) %>

    <% if !@post.published? %>
    <%= button_to("Publish", publish_post_path(@post), :params => {:published => "protect"}, :method => :patch) %>
    <% end %>
    
    <% if @post.flaged? %>
    <%= button_to("Unflag This Post", unflag_post_path(@post), method: :post, data: { confirm: 'Are you certain you want to unflag this?' }) %>
    <% end %>
    <%= link_to("User", reporting_user_path(@post.user), :method => :get) %>
<% end %>



<% if !@flags.blank? %>
<div> Reported messages: <%= @post.flag_number %></div>
<div>
  <% @flags.each do |flag| %>
    <%= flag.flag_message %>
    <%= flag.created_at %>
  <% end %>
</div>
<% end %>

<%= javascript_tag do %>
  $(function() {
    $("time.timeago").timeago();
  });
<% end %>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><b><%= @post.title %></b></h3>
  </div>
  <div class="panel-body">
    <p><b>City: </b><%= @post.city %> - <b>Postal code: </b><%= @post.postal_code %></p>
    <!--<p>Postal code: <%= @post.postal_code %></p>-->
    <p><b>Meeting date: </b><%= l @post.meeting_date %></p>
    <p><b>Description: </b></p>
    <p><%= simple_format(@post.description) %></p>
  </div>
    <div class="panel-footer">
    <small>
    <span class="glyphicon glyphicon-time"></span>
    Posted <%= timeago(@post.created_at) %>
    </small>
    </div>
</div>

<% if owner(@post) %>
    <%= link_to("Edit Your Post", edit_post_path(@post), :method => :get) %>
    <%= button_to("Delete Your Post", post_path(@post), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }) %>
<% end %>

<% if !@message.blank? %>
  <%= form_for(@message, url: send_message_post_path(@post)) do |f| %>
  <div class="form-group">
  <%= f.text_area :content, class: "form-control", placeholder: "write a message" %>
  <%= f.invisible_captcha :verification %>
  <%= f.submit "send", class: "btn btn-primary" %>
  <% end %>
  </div>
<% else %>
<% if !owner(@post) %>
<div><p> Already respond to this post!</p></div>
<% end %>
<% end %>
<div>  
<% if current_user != @user %>
  <%= link_to "Report this post", flag_post_path(@post) %>
<% end %>

<% if current_user.admin? %>
  <%= link_to "Detail for the post reporting", reporting_post_path(@post) %>
  <%= link_to "Detail for the user reporting", reporting_user_path(@post.user) %>
<% end %>
</div>

<%= javascript_tag do %>
  $(function() {
    $("time.timeago").timeago();
  });
<% end %>
    

app/views/posts/unpublished.html.erb
<div class="container">
  <div class="row">
		<div class="well">
		  <h1 class="text-center">Posts</h1>
        <div class="btn-group" role="group" aria-label="Default Button Groups">
        <% if current_user.admin? %>
  	    <%= link_to "All posts", posts_path, class: "btn btn-default" %>
  	    <%= link_to "Waiting (#{@unpublished_posts})", unpublished_posts_path, class: "btn btn-default-active" %>
  	    <%= link_to "Signaled Posts(#{@flaged_posts})", flaged_posts_path, class: "btn btn-default" %>
  	    <%= link_to "Signaled Users(#{@reported_users})", reported_users_path, class: "btn btn-default" %>
  	    <%= link_to "Blocked Users", blocked_users_path, class: "btn btn-default" %>
  	    <%= link_to "Search for a user", searching_form_users_path, class: "btn btn-default" %>
  	    <%= link_to "Users", users_path, class: "btn btn-default" %>
        <% end %>
        </div>
      <% if !@posts.blank? %>
        <%= will_paginate %>
        <div class="list-group">
          <%= render partial: 'posts/post_unpublished', collection: @posts, as: :post %>
        </div>
        <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>